name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DATABASE_URL: mongodb://localhost:27018/test?directConnection=true
  JWT_SECRET: supersecret

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.16.0'
      - name: Run tests
        run: pnpm test:int:ci
